# Generated by Django 4.1.3 on 2022-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
